%% build_simulink_model.m  --  construct asteria_bench.slx programmatically
% The model is generated by this script rather than shipped as a binary, so it can be diffed,
% reviewed, and regenerated after any change to the parameters. Run after bench_init_3dof,
% optimize_maneuver and build_schedule (the blocks read P from the base workspace).
%
% Structure:
%   Clock ---------------------------------+------------------+
%   Constant d --> [PlantDeriv] --> [1/s] --+--> [Sensors] --> [EKF] --> [Ctrl] --> [Sat] --+
%                      ^                                         ^                         |
%                      +------------------- i_app ---------------+-------------------------+
%                                                    (via Unit Delay into the EKF)
% The Unit Delay breaks the algebraic loop EKF -> Ctrl -> Sat -> EKF, and is also physically
% right: the filter propagates with the current that was applied over the last step.

assert(isfield(P,'sched'), 'run bench_init_3dof, optimize_maneuver and build_schedule first');
mdl = 'asteria_model';   % must match the .slx file name
if bdIsLoaded(mdl), close_system(mdl, 0); end
if exist([mdl '.slx'], 'file'), delete([mdl '.slx']); end   % regenerate from scratch; avoids the shadowing warning
new_system(mdl);
set_param(mdl, 'Solver','ode4', 'FixedStep','P.Ts', 'StopTime','1.5*P.ref.T', ...
               'SolverType','Fixed-step');

add_block('simulink/Sources/Clock',                        [mdl '/Clock']);
add_block('simulink/Sources/Constant',                     [mdl '/Disturbance']);
add_block('simulink/Sources/Constant',                     [mdl '/NoiseOn']);
add_block('simulink/User-Defined Functions/MATLAB Function',[mdl '/PlantDeriv']);
add_block('simulink/Continuous/Integrator',                [mdl '/States']);
add_block('simulink/User-Defined Functions/MATLAB Function',[mdl '/Sensors']);
add_block('simulink/Discrete/Unit Delay',                  [mdl '/i_prev']);
add_block('simulink/User-Defined Functions/MATLAB Function',[mdl '/EKF']);
add_block('simulink/User-Defined Functions/MATLAB Function',[mdl '/Controller']);
add_block('simulink/Discontinuities/Saturation',           [mdl '/Sat']);
add_block('simulink/Sinks/To Workspace',                   [mdl '/state_log']);
add_block('simulink/Sinks/To Workspace',                   [mdl '/est_log']);
add_block('simulink/Sinks/To Workspace',                   [mdl '/i_log']);
add_block('simulink/Math Operations/Gain',                 [mdl '/pick_gap']);
add_block('simulink/Logic and Bit Operations/Relational Operator', [mdl '/contact']);
add_block('simulink/Sources/Constant',                     [mdl '/zero_gap']);
add_block('simulink/Sinks/Stop Simulation',                [mdl '/stop_on_contact']);

set_param([mdl '/Disturbance'], 'Value','P.test.d');
set_param([mdl '/NoiseOn'],     'Value','P.test.noise');
set_param([mdl '/States'],      'InitialCondition','[P.traj.x0;0;0;0;0;0]');
set_param([mdl '/i_prev'],      'InitialCondition','0', 'SampleTime','P.Ts');
set_param([mdl '/Sat'],         'UpperLimit','P.i_sat', 'LowerLimit','-P.i_sat');
set_param([mdl '/state_log'],   'VariableName','s_log',  'SaveFormat','Array');
set_param([mdl '/est_log'],     'VariableName','xh_log', 'SaveFormat','Array');
set_param([mdl '/i_log'],       'VariableName','i_log',  'SaveFormat','Array');
set_param([mdl '/pick_gap'],    'Gain','[1 0 0 0 0 0]', 'Multiplication','Matrix(K*u)');
set_param([mdl '/contact'],     'Operator','<=');
set_param([mdl '/zero_gap'],    'Value','0');

scripts = { 'PlantDeriv', sprintf(['function ds = fcn(s, i, d)\n' ...
    'coder.extrinsic(''sl_plant'');\n' ...
    'ds = zeros(6,1);\n' ...
    'ds = sl_plant(s, i, d);\n' ...
    'end']);
  'Sensors', sprintf(['function z = fcn(s, t, noise_on)\n' ...
    'coder.extrinsic(''sl_sensors'');\n' ...
    'z = zeros(4,1);\n' ...
    'z = sl_sensors(s, t, noise_on);\n' ...
    'end']);
  'EKF', sprintf(['function xh = fcn(i_app, z, t)\n' ...
    'coder.extrinsic(''sl_ekf'');\n' ...
    'xh = zeros(10,1);\n' ...
    'xh = sl_ekf(i_app, z, t);\n' ...
    'end']);
  'Controller', sprintf(['function i_cmd = fcn(xh, t)\n' ...
    'coder.extrinsic(''sl_ctrl'');\n' ...
    'i_cmd = zeros(4,1);\n' ...
    'i_cmd = sl_ctrl(xh, t);\n' ...
    'end']) };
rt = sfroot;
for k = 1:size(scripts,1)
    ch = rt.find('-isa','Stateflow.EMChart','Path',[mdl '/' scripts{k,1}]);
    ch.Script = scripts{k,2};
    if ~strcmp(scripts{k,1},'PlantDeriv')     % everything but the plant runs discrete at P.Ts
        ch.ChartUpdate = 'DISCRETE';
        ch.SampleTime  = 'P.Ts';
    end
end

% ---- Embedded mode: the EKF and Controller blocks call the code-generation functions directly.
% No coder.extrinsic, so these two blocks are exactly what gets compiled for the target; the
% plant and sensor blocks stay simulation-only. The parameter struct pc is a block PARAMETER,
% rebuilt from P by the model's InitFcn at every simulation start, so it cannot go stale.
if ~isfield(P,'sim') || ~isfield(P.sim,'embedded') || P.sim.embedded
    set_param(mdl, 'InitFcn', 'pc = make_cg_params(P);');
    pc = make_cg_params(P); %#ok<NASGU>
    emb = { 'EKF', sprintf(['function xh_out = fcn(i_app, z, t, pc)\n' ...
        'persistent xh Pk Kp k\n' ...
        'if isempty(xh) || t <= 0\n' ...
        '    xh = pc.x_init;  Pk = pc.P0;  Kp = zeros(3);  k = 0;\n' ...
        'end\n' ...
        'k = k + 1;\n' ...
        '[xh, Pk, Kp] = cg_ekf_step(xh, Pk, Kp, i_app, z, pc, (k == 1) || (mod(k,20) == 0));\n' ...
        'xh_out = xh;\n' ...
        'end']);
      'Controller', sprintf(['function i_cmd = fcn(xh, t, pc)\n' ...
        '[i_cmd, ~] = cg_ctrl(xh, t, pc);\n' ...
        'end']) };
    for k = 1:size(emb,1)
        ch = rt.find('-isa','Stateflow.EMChart','Path',[mdl '/' emb{k,1}]);
        ch.Script = emb{k,2};
        dp = ch.find('-isa','Stateflow.Data','Name','pc');
        dp.Scope = 'Parameter';
    end
    fprintf('embedded mode: EKF and Controller blocks call cg_ekf_step / cg_ctrl (no extrinsic)\n');
end

% Signal dimensions cannot be inferred round the plant loop (PlantDeriv -> Integrator ->
% PlantDeriv), so every port size is declared explicitly. Leave these in: without them the
% model compiles the state vector as a scalar and the plant errors on s(1:3).
sizes = { 'PlantDeriv', {'s',6; 'i',4; 'd',3; 'ds',6};
          'Sensors',    {'s',6; 't',1; 'noise_on',1; 'z',4};
          'EKF',        {'i_app',4; 'z',4; 't',1};
          'Controller', {'xh',10; 't',1; 'i_cmd',4} };
for k = 1:size(sizes,1)
    ch = rt.find('-isa','Stateflow.EMChart','Path',[mdl '/' sizes{k,1}]);
    for j = 1:size(sizes{k,2},1)
        dd = ch.find('-isa','Stateflow.Data','Name',sizes{k,2}{j,1});
        dd.Props.Array.Size = num2str(sizes{k,2}{j,2});
    end
end

add_line(mdl, 'PlantDeriv/1', 'States/1',    'autorouting','on');
add_line(mdl, 'States/1',     'PlantDeriv/1','autorouting','on');   % state feedback into the
                                   % derivative: without this Simulink grounds the port and the plant
                                   % silently integrates from a zero state.
add_line(mdl, 'States/1',     'Sensors/1',   'autorouting','on');
add_line(mdl, 'Clock/1',      'Sensors/2',   'autorouting','on');
add_line(mdl, 'NoiseOn/1',    'Sensors/3',   'autorouting','on');
add_line(mdl, 'i_prev/1',     'EKF/1',       'autorouting','on');
add_line(mdl, 'Sensors/1',    'EKF/2',       'autorouting','on');
add_line(mdl, 'Clock/1',      'EKF/3',       'autorouting','on');
add_line(mdl, 'EKF/1',        'Controller/1','autorouting','on');
add_line(mdl, 'Clock/1',      'Controller/2','autorouting','on');
add_line(mdl, 'Controller/1', 'Sat/1',       'autorouting','on');
add_line(mdl, 'Sat/1',        'i_prev/1',    'autorouting','on');
add_line(mdl, 'Sat/1',        'PlantDeriv/2','autorouting','on');
add_line(mdl, 'Disturbance/1','PlantDeriv/3','autorouting','on');
add_line(mdl, 'States/1',     'state_log/1', 'autorouting','on');
add_line(mdl, 'EKF/1',        'est_log/1',   'autorouting','on');
add_line(mdl, 'Sat/1',        'i_log/1',     'autorouting','on');

add_line(mdl, 'States/1',     'pick_gap/1',  'autorouting','on');
add_line(mdl, 'pick_gap/1',   'contact/1',   'autorouting','on');
add_line(mdl, 'zero_gap/1',   'contact/2',   'autorouting','on');
add_line(mdl, 'contact/1',    'stop_on_contact/1', 'autorouting','on');

% Every wrapper caches P on first call. Flush them at the start of EVERY simulation, or a
% changed start gap, calibration or latency is silently ignored until MATLAB restarts.
set_param(mdl, 'StartFcn', 'clear sl_plant sl_sensors sl_ekf sl_ctrl asteria_ekf');

Simulink.BlockDiagram.arrangeSystem(mdl);
save_system(mdl);
fprintf('built %s.slx  (solver %s, step %s, stop %s)\n', mdl, ...
        get_param(mdl,'Solver'), get_param(mdl,'FixedStep'), get_param(mdl,'StopTime'));
